// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Process from "process";

function $$default(param) {
  if (Fs.existsSync("./gridsome.config.js")) {
    return 0;
  } else {
    console.error("Not in the root of a Gridsome project!");
    return Process.exit(1);
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* fs Not a pure module */
